// Generated by LiveScript 1.2.0
(function(){
  var index, fingerprint, FingerPrinter;
  require('../test_setup');
  index = require('../../');
  fingerprint = index.fingerprint;
  FingerPrinter = fingerprint.FingerPrinter;
  describe('FingerPrinter', function(){
    var accessRequest, fingerPrinter;
    fingerPrinter = function(ar, debug){
      debug == null && (debug = true);
      return new FingerPrinter(ar, debug);
    };
    before(function(){
      return accessRequest = {
        user: {
          name: 'Kris'
        },
        action: 'read'
      };
    });
    return describe('fingerprint', function(){
      return specify('has method access-hash', function(){
        var res;
        res = fingerPrinter(accessRequest).fingerprint();
        return res.should.eql('ea4fd60a6dc4c0f9b0cc7637f7f5617e');
      });
    });
  });
}).call(this);
